# docker-compose.yml

version: '3.8'

services:
  webserver:
    build: .
    container_name: php-apache
    volumes:
      - ./repos/maxi/tapir:/var/www/html/maxi
      - ./repos/pedro/tapir:/var/www/html/pedro
      - ./repos/fernando/tapir:/var/www/html/fernando
      - ./repos/facundo/tapir:/var/www/html/facundo
      - ./repos/jpablo/tapir:/var/www/html/jpablo
      - ./repos/jluis/tapir:/var/www/html/jluis
      - ./repos/inaki/tapir:/var/www/html/inaki
      - webdata:/var/www/html
      - weblogs:/var/log/apache2
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/maxi.conf:/etc/apache2/sites-available/maxi.conf
      - ./config/pedro.conf:/etc/apache2/sites-available/pedro.conf
      - ./config/fernando.conf:/etc/apache2/sites-available/fernando.conf
      - ./config/facundo.conf:/etc/apache2/sites-available/facundo.conf
      - ./config/jpablo.conf:/etc/apache2/sites-available/jpablo.conf
      - ./config/jluis.conf:/etc/apache2/sites-available/jluis.conf
      - ./config/inaki.conf:/etc/apache2/sites-available/inaki.conf
      - ./config/hosts:/etc/hosts
    ports:
      - "8081:80"
      - "2222:2222"
    networks:
      - devenv-net
      - dbnet
    depends_on:
      - db

  db:
    image: postgres:14.12
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    networks:
      - dbnet

networks:
  devenv-net:
    driver: bridge
  dbnet:
    driver: bridge

volumes:
  pgdata:
   driver: local
  webdata:
   driver: local
  weblogs:
    driver: local
